name: run-docker1.yml

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  vm:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo This job does not specify a container.
          echo It runs directly on the virtual machine.
        name: Run on VM

  container1:
    runs-on: ubuntu-latest
    container: node:10.16-jessie
    steps:
      - run: |
          echo This job does specify a container.
          echo It runs in the container instead of the VM.
        name: Run in container1

  container2:
    runs-on: ubuntu-latest
    container: squidfunk/mkdocs-material
    steps:
      - uses: actions/checkout@v2
      - run: |
          # echo "START DISPLAYING README.MD"
          # cat README.MD
          # echo "END DISPLAYING README.MD"
          echo "/github/home"
          ls -la  "/github/home"
          echo "/github/workflow"
          ls -la  "/github/workflow"
          echo "/github/workspace"
          ls -la  "/github/workspace"
        name: Run in container2